### ISSUE TITLE
TODO for version 1.0

### ISSUE THREAD

**Issue by senid231** [activeadmin-plugins/capybara_active_admin#1]
* click on row actions
* check row action present
* check specific filter present
* fill filters
* click filter button
* select rows in table
* click on batch actions
* accept/decline confirmation modal
* check data in attributes_table
* check status_tag (color class, text)
* fill nested has_many form
* switch tabs
* check sidebar content
* wiki for usecases
* documentation for all methods of DSL

**Comment by senid231** [comment]
I think it will be useful to add something like
```ruby
with_table_for('users') do
  expect(page).to have_table_row(user.id).with_cells(
    id: user.id,
    full_name: user.full_name,
    status: 'ENABLED' # for status tag
  )
end
```

**Comment by Fivell** [comment]
@senid231  how about using capybaras within 
```
within table_for('users')
```

**Comment by senid231** [comment]
moved to https://github.com/activeadmin-plugins/capybara_active_admin/projects/1
